language: php

php:
  - 7.2

services:
  - mongodb
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

before_script:
  - echo "extension=mongodb.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

before_install:
  - sudo apt-get update
  - sudo apt-get install -y unzip
  - wget -O /tmp/UOLocation.zip https://ultimaphp.nyc3.digitaloceanspaces.com/ultimaphpmuls.zip
  - unzip /tmp/UOLocation.zip -d ./UOLocation

script:
  - php startserver.php test

# after_success:
#   - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
#   - export REPO=hideout/ultimaphp
#   - export TAG=$(if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi)
#   - docker build -f Dockerfile -t $REPO:$COMMIT .
#   - docker tag $REPO:$COMMIT $REPO:$TAG
#   - docker tag $REPO:$COMMIT $REPO:build-$TRAVIS_BUILD_NUMBER
#   - docker push $REPO

notifications:
  irc: "irc.youhide.com.br#ultimaphp"
