language: php

php:
  - 7.2

services:
  - mongodb
  - docker

before_script:
  - echo "extension=mongodb.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

before_install:
  - sudo apt-get update
  - sudo apt-get install -y unzip
  - wget -O /tmp/UOLocation.zip https://ultimaphp.nyc3.digitaloceanspaces.com/ultimaphpmuls.zip
  - unzip /tmp/UOLocation.zip -d ./UOLocation

script:
  - php startserver.php test
  - docker build -t ultimephp .
  - $(echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin)
  - docker tag ultimaphp hideout/ultimaphp
  - docker push hideout/ultimaphp

notifications:
  irc: "irc.youhide.com.br#ultimaphp"
