language: php

php:
  - 7.2

before_install:
  - sudo apt-get update
  - sudo apt-get install -y unzip
  - pecl install mongodb-1.5.2
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - wget -O UOLocation.zip  https://ultimaphp.nyc3.digitaloceanspaces.com/ultimaphpmuls.zip
  - unzip UOLocation.zip -d UOLocation

script: php startserver.php

notifications:
  irc: "irc.youhide.com.br#ultimaphp"
