version: '3.1'

services:

  uphp-server:
    build: ./
    ports:
      - "2593:2593"

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    # volumes:
      # - ./data/local:/var/lib/data

  mongo-seed:
    build: ./tools/Mongo_Database
